spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: "naver"
            client-id: "pgt2BNNA4D0k6A7HSJUB"
            client-secret: "ldfb9IOCYM"
            redirect-uri: "http://localhost/login/callback/naver"
            authorization-grant-type: "authorization_code"
            scope:
              - email
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-name-attribute: "response"