spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    script-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://43.202.127.161:3306/klj
    username: klj
    password: maria
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      #      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  com.sillimfive.mymap: debug


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

